version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: messages
      POSTGRES_PASSWORD: messages
      POSTGRES_USER: messages
    volumes:
      - ./init_db_2.sql:/docker-entrypoint-initdb.d/init_db_2.sql

