version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

volumes:
  mysql:
  wordpress: